name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Flutter project
        run: flutter create .

      - name: Use our app code
        run: |
          mkdir -p lib
          cp main.dart lib/main.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        env:
          GRADLE_OPTS: -Dorg.gradle.vfs.watch=false
        run: |
          flutter clean
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: rooh-mashwar-apk
          path: build/app/outputs/flutter-apk/app-release.apk
